import { Download, Eye, FileText } from "lucide-react";
import { useState } from "react";
import { documents } from "../data/projectData";

const categories = ["All", "Proposal", "Final Report", "Other"];
export default function Documents() {
  const [active, setActive] = useState("All");
  const visible = active === "All" ? documents : documents.filter(doc => doc.category === active);
  return <section className="bg-[#eef1e9] px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><p className="eyebrow">07 / The archive</p><div className="flex flex-wrap items-end justify-between gap-5"><h2 className="section-title mt-4">Project <span>Documents</span></h2><div className="flex flex-wrap gap-2">{categories.map(category => <button key={category} onClick={() => setActive(category)} className={`rounded-full px-4 py-2 text-xs font-bold transition ${active === category ? "bg-[#1f6044] text-white" : "bg-white text-[#6c7a70] hover:bg-[#dfead5]"}`}>{category}</button>)}</div></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.map(doc => <article key={doc.title} className="rounded-2xl border border-[#dce4d9] bg-white p-5 transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-[#fff0ed] text-[#d05f50]"><FileText size={21} /></div><div className="min-w-0 flex-1"><h3 className="text-sm font-bold text-[#1e3027]">{doc.title}</h3><span className="mt-2 inline-block rounded-full bg-[#edf6df] px-2 py-1 font-mono text-[10px] font-bold text-[#56823c]">{doc.id || "GROUP"}</span></div></div><div className="mt-5 flex gap-2 border-t border-[#edf0ea] pt-4"><a href={doc.link} className="inline-flex flex-1 items-center justify-center gap-2 rounded-lg bg-[#1f6044] px-3 py-2 text-xs font-bold text-white transition hover:bg-[#154d35]"><Eye size={14} /> View</a><a href={doc.link} download className="inline-flex flex-1 items-center justify-center gap-2 rounded-lg border border-[#b9ccb0] px-3 py-2 text-xs font-bold text-[#56823c] transition hover:bg-[#edf6df]"><Download size={14} /> Download</a></div></article>)}</div></div></section>;
}
