import { Check, Clock } from "lucide-react";
import { useState } from "react";
import { milestones } from "../data/projectData";

const statusStyles = { completed: "bg-[#e4f1d8] text-[#4d8137]", "in-progress": "bg-[#fff1bf] text-[#8d6d13]", upcoming: "bg-[#e9eeea] text-[#68776d]" };
const statusLabels = { completed: "Completed", "in-progress": "In Progress", upcoming: "Upcoming" };

export default function Milestones() {
  const [selectedTitle, setSelectedTitle] = useState(milestones[0].title);
  const selected = milestones.find(item => item.title === selectedTitle) || milestones[0];
  return <section className="bg-[#fbfaf5] px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-5xl"><p className="eyebrow">05 / The journey</p><h2 className="section-title mt-4">Project <span>Milestones</span></h2><div className="mt-10 grid gap-5 md:grid-cols-[280px_1fr]"><label className="text-sm font-bold text-[#1e3027]">Explore a milestone<select value={selectedTitle} onChange={event => setSelectedTitle(event.target.value)} className="mt-3 w-full rounded-xl border border-[#dce5d8] bg-white px-4 py-3 font-normal outline-none transition focus:border-[#6b9c52]">{milestones.map(item => <option key={item.title}>{item.title}</option>)}</select></label><article className="rounded-2xl border border-[#dce5d8] bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center gap-3"><span className="font-mono text-xs font-bold uppercase tracking-wider text-[#6b9c52]">{selected.date}</span><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusStyles[selected.status]}`}>{statusLabels[selected.status]}</span><span className="rounded-full bg-[#edf6df] px-3 py-1 text-xs font-bold text-[#56823c]">Marks: {selected.marks}</span></div><h3 className="mt-3 text-2xl font-bold text-[#1e3027]">{selected.title}</h3><p className="mt-3 leading-7 text-[#68776d]">{selected.description}</p><p className="mt-3 border-t border-[#edf0ea] pt-4 text-sm leading-6 text-[#78867d]">{selected.details}</p></article></div><div className="relative mt-14"><div className="absolute bottom-5 left-[17px] top-5 w-px bg-[#dce5d8] md:left-1/2" />{milestones.map((item, index) => <div key={item.title} className="relative mb-9 flex gap-5 last:mb-0 md:grid md:grid-cols-2 md:gap-14"><div className={`z-10 mt-1 flex h-9 w-9 shrink-0 items-center justify-center rounded-full border-4 border-[#fbfaf5] ${item.status === "completed" ? "bg-[#6b9c52] text-white" : item.status === "in-progress" ? "bg-[#d4ae42] text-white" : "bg-white text-[#9ba59d] ring-1 ring-[#cdd7cd]"} md:absolute md:left-1/2 md:-translate-x-1/2`}>{item.status === "completed" ? <Check size={15} strokeWidth={3} /> : <Clock size={15} />}</div><div className={`${index % 2 === 0 ? "md:col-start-1 md:text-right" : "md:col-start-2 md:row-start-1"}`}><div className="flex flex-wrap items-center gap-2 md:justify-end"><p className="font-mono text-xs font-bold uppercase tracking-[0.15em] text-[#6b9c52]">{item.date}</p><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-wider ${statusStyles[item.status]}`}>{statusLabels[item.status]}</span><span className="rounded-full bg-[#f0f3ed] px-2 py-1 text-[10px] font-bold text-[#78867d]">{item.marks}</span></div><h3 className="mt-2 text-lg font-bold text-[#1e3027]">{item.title}</h3><p className="mt-2 text-sm leading-6 text-[#718078]">{item.description}</p></div></div>)}</div></div></section>;
}
